Add CloudWatch configuration file
nlpsandbox/nlpsandbox-infra pull request #31
Opened 2021-08-10 13:47 UTC by tschaffter

Add CW agent configuration file used on EC2 instances (data node, controller, elk).

This configuration file was generated using `sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard`. The options selected are the mostly the ones listed in the article [Cloudwatch Agent Manual Install](https://www.wellarchitectedlabs.com/cost/200_labs/200_aws_resource_optimization/4_memory_plugin/).

@thomasyu888 There's probably a better place for this file than the root directory of this GH repo. Let me know if you want me to place it somewhere else.

2021-08-10 14:25 UTC, thomasyu888 commented
@tschaffter Can you add the description you posted to the readme so that we have record of how to set up cloudwatch.

2021-08-12 02:41 UTC, tschaffter commented
@thomasyu888 I added the instructions on how to install and run CW to the README.

2021-08-12 02:42 UTC, tschaffter commented
@thomasyu888 Why is the test failing? Do you know how to fix the issue?

2021-08-12 03:17 UTC, thomasyu888 requested changes

2021-08-12 03:17 UTC, thomasyu888 commented on README.md
> +[Download the CloudWatch agent for Ubuntu (x86-64)]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html
```suggestion
[Download the CloudWatch agent for Ubuntu (x86-64)]: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html

```

2021-08-12 03:18 UTC, thomasyu888 approved these changes

2021-08-12 03:19 UTC, merged